# Generated by Django 5.1.8 on 2025-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_resource_options'),
        ('room', '0003_alter_room_options_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(related_name='room', to='additional.resource'),
        ),
    ]
