# Generated by Django 5.1.8 on 2025-05-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
