# Generated by Django 5.1.8 on 2025-05-18 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_phone_alter_office_rooms'),
        ('room', '0006_alter_reservation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='office.office'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='room.room'),
        ),
    ]
