# Generated by Django 5.1.8 on 2025-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_resource_options'),
        ('room', '0007_room_office_alter_reservation_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, related_name='room', to='additional.resource'),
        ),
    ]
