# Generated by Django 5.1.8 on 2025-05-18 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='participants_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
