# Generated by Django 5.1.8 on 2025-05-18 01:15

import apps.office.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('stats', models.BooleanField(db_index=True, default=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[apps.office.models.validate_br_document], verbose_name='CPF/CNPJ')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?[\\d\\-\\(\\) ]{8,20}$')], verbose_name='Telefone')),
                ('rooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Salas')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
    ]
