# Generated by Django 5.1.8 on 2025-05-18 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+?[\\d\\-\\(\\) ]{8,20}$')], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='office',
            name='rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Rooms'),
        ),
    ]
