# Generated by Django 5.1.8 on 2025-05-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_phone_alter_office_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
