# Generated by Django 5.1.8 on 2025-05-18 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+?[\\d\\-\\(\\) ]{8,20}$')], verbose_name='Telephone'),
        ),
    ]
